@extends('layout')
@section('title') Two-Factor Authentication @stop
@section('page_heading') Two-Factor Authentication @stop

@section('header_styles')

@stop

@section('footer_scripts_notification')
    <script>
        function popUpConfirm(){
            $('#fa2form').submit();
        }
    </script>
@stop

{{-- page heading --}}

@section('content')
    <script src="{{asset('js/jquery.min.js')}}"></script>
    <script>
        function popUpConfirm(){
            $('#fa2form').submit();
        }
    </script>
    <div class="user-information containt-box shadow">
        <div class="row">
            <div class="col-lg-6 text-center">
                @if(!$user->is_two_factor_enabled)
                    <form class="form-horizontal" id="fa2form" method="POST" action="{{ url('enable-2fa') }}">
                        @else
                            <form class="form-horizontal" id="fa2form" method="POST"  action="{{ url('disable-2fa') }}">
                                @endif
                                {{ csrf_field() }}
                                @if(!$user->is_two_factor_enabled)
                                    <h2>SCAN</h2>
                                    <p class="sub-title">Please scan this barcode using <strong>Google
                                            Authenticator</strong><!--  or <strong>Authy</strong> --> client Application
                                        and Click Enable Button</p>
                                    <p><strong>Note: Please copy this secret key for future use.</strong></p>
                                    <div class="qr-code"><img src="{{ $QR_Image }}"/></div>
                                    @if($secret)<p><strong>Secret Key: </strong> {{ $secret }}</p>@endif


                                    <input type="hidden" name="secret_key" value="{{$secret}}"/>
                                    <input type="hidden" name="user_id" value="{{encrypt($user->id)}}"/>
                                    <p>

                                        <button type="button" id="submitBtn" data-toggle="modal"  id="" class="btn btn-primary btn-lg checkStep2fcBtn" onclick="popUpConfirm()">Enable
                                            Two Factor Authentication
                                        </button>
                                    </p>
                                @else
                                    <button type="submit" id="checkStep2fcBtn" class="btn btn-primary btn-lg checkStep2fcBtn">Disable
                                        Two Factor Authentication
                                    </button>
                                @endif


                                <p>Google Authenticator generates 2-Step Verification codes on your phone. 2-Step
                                    Verification provides stronger security for account by requiring a second step
                                    of verification when you sign in. In addition to your password, you’ll also need
                                    a code generated by the Google Authenticator app on your phone.</p>

                            </form>

            </div>

            <div class="col-lg-6">
                <div class="auth-box document">
                    <h3 class="box-title">HOW IT WORKS</h3>
                    <h5>Configure Two-Factor Authentication</h5>
                    <p>
                        Two Factor Authentication(2FA) is an extra layer of security that requires not only
                        a password and username but also something that only, and only, that user has on
                        them, i.e. a piece of information only they should know or have immediately to hand
                        - such as a physical token.
                    </p>
                    <h5>1. Install a Free Two Factor App on Your Mobile Device</h5>
                    <p>
                        To use Two Factor Authentication with TOTP(time-based one-time password) you need to
                        install and configure an app on your device. The app will then supply you with
                        additional authentication codes required to access your site.
                    </p>

                    <h5>2. Scan the QR Code</h5>
                    <p>
                        Using the app you just installed, scan the QR code below.
                    </p>
                    <p><img src="{{asset('img/google-auth.png')}}" width="150"></p>
                    <p class="text-uppercase">
                        <strong><a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank"><i
                                        class="fa fa-apple"></i> Download</a> on iOS</strong><br>
                        <strong><a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en" target="_blank"><i
                                        class="fa fa-android"></i> Download</a> on Android</strong>
                    </p>

                </div>
            </div>
        </div>
    </div>




    <!-- Alert step profile Modal -->
    <div class="modal fade  in modal-alert" id="confirm-submit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Confirmation!</h4>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

                </div>
                <div class="modal-body">
                    Have you scanned the 2FA barcode?

                    Do not close the window before you have the secret key saved!

                    IMPORTANT! Save your secret key in a safe place. You will need it if you lose your phone or want to reset 2FA.
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-sm btn-default" style="width: 100px;">No</button>
                    <button type="button" data-dismiss="modal" class="btn btn-sm btn-primary" style="width: 100px;" onclick="popUpConfirm()">Yes</button>
                </div>
            </div>
        </div>
    </div>



@stop